name: Branch CI

on:
  push:
    branch:
      - TicTacToe/**

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@4.1.7
    - uses: actions/setup-java@4.2.1
      with:
        java-version: 21
        distribution: temurin
    - run: mvn test --file pom.xml
